enable-module-update = true
parallel-jobs = 1
compression-level = 9
include-stock = "split"
riplib = true
cli-version = "dev"


[YouTube-Morphe]
app-name = "YouTube"
brand = "Morphe"
build-mode = "both"
excluded-patches = "'Custom branding'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
version = "latest"

[YouTube-Music-Morphe]
app-name = "YouTube Music"
brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
version = "latest"

[Reddit-Morphe]
app-name = "Reddit"
brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
version = "latest"

[X-Piko]
app-name = "X"
brand = "Piko"
pkg-name = "com.twitter.android"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
version = "latest"
patches-source = "crimera/piko-newx"
patches-version = "dev"
included-patches = "'NewX: Restore Twitter branding'"

[Instagram-Piko]
app-name = "Instagram"
brand = "Piko"
pkg-name = "com.instagram.android"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
version = "447.0.0.55.81"
patches-source = "crimera/piko"
patches-version = "dev"

[Facebook-Hush]
app-name = "Facebook"
brand = "Hush"
pkg-name = "com.facebook.katana"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
dpi = "240-640dpi"
version = "auto"
patches-source = "SysAdminDoc/Hushfacebook"
patches-version = "latest"
apkmirror-type = "bundle"

[Messenger-Hush]
app-name = "Messenger"
brand = "Hush"
pkg-name = "com.facebook.orca"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger"
version = "auto"
patches-source = "SysAdminDoc/HushMessenger"
patches-version = "latest"
apkmirror-type = "apk"

[Google-Photos-Morphe]
app-name = "Google Photos"
brand = "Morphe"
pkg-name = "com.google.android.apps.photos"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
version = "auto"
patches-source = "Akash-Sriram/morphe-google-photos"
patches-version = "latest"
excluded-patches = "'Custom Morphe branding'"